name: Unit Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9-amazoncorretto-21

    steps:
    - uses: actions/checkout@v4

    - name: Build and run tests with Maven
      run: mvn clean test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports/ 